trigger:
- main
variables:
 buildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
         vmImage: windows-latest
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '7.0.306'
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec:
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '**/*.sln'
            arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
            zipAfterPublish: true
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          condition: succeeded()